config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['prefix' => 'admin', 'controller' => 'Usuarios', 'action' => 'login']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
//    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

Router::prefix('admin', function ($routes) {
    // All routes here will be prefixed with `/admin`
    // And have the prefix => admin route element added.

    $routes->connect('/', ['controller' => 'Home', 'action' => 'index']);
    $routes->connect('/logout', ['controller' => 'Usuarios', 'action' => 'logout']);
    $routes->connect('/login', ['controller' => 'Usuarios', 'action' => 'login']);
    $routes->setExtensions(['xlsx']);
    $routes->fallbacks(DashedRoute::class);
});

src/Model/Table/ArquivosTable.php
<?php

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Datasource\ConnectionManager;
use Cake\I18n\Time;
use Cake\Core\Configure;
use Cake\ORM\TableRegistry;

/**
 * Arquivos Model
 *
 * @method \App\Model\Entity\Arquivo get($primaryKey, $options = [])
 * @method \App\Model\Entity\Arquivo newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Arquivo[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Arquivo|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Arquivo|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Arquivo patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Arquivo[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Arquivo findOrCreate($search, callable $callback = null, $options = [])
 */
class ArquivosTable extends AppTable {

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config) {
        parent::initialize($config);

        $this->setTable('arquivos');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Xety/Cake3Upload.Upload', [
            'fields' => [
                'arquivo' => [
                    'path' => '/upload/arquivos/:md5',
                ]
            ],
            'suffix' => '_upload',
            'prefix' => '../'
        ]);

        $this->belongsTo('Usuario', [
            'foreignKey' => 'usuario_id',
            'className' => 'Usuarios',
            'joinType' => 'LEFT'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator) {
        $validator
                ->integer('id')
                ->allowEmpty('id', 'create');

        $validator
                ->scalar('arquivo')
                ->maxLength('arquivo', 255)
                ->requirePresence('arquivo', 'create')
                ->notEmpty('arquivo');

        $validator
                ->scalar('tipo')
                ->allowEmpty('tipo');

        $validator
                ->scalar('titulo')
                ->maxLength('titulo', 255)
                ->allowEmpty('titulo');

        $validator
                ->dateTime('criado')
                ->allowEmpty('criado');

        return $validator;
    }

    public function novo() {
        return $this->newEntity();
    }

    public function buscar($id) {
        return $this->get($id, ['contain' => ['Usuario']]);
    }

    public function salvar($arquivo, $tipo = '', $titulo = '', ...$args) {

        $conn = ConnectionManager::get('default');
        $conn->begin();
        $userSession = Configure::read('SessionUser');

        ini_set('post_max_size', '64M');
        ini_set('upload_max_filesize', '64M');

        $existe = $this
            ->exists([
                'tipo' => $tipo,
                'importando' => false,
                'importado' => false,
                'criado >=' => Time::now()->i18nFormat('yyyy-MM-dd 00:00:00'),
                'criado <=' => Time::now()->i18nFormat('yyyy-MM-dd 23:59:59'),
            ]);

        if ($existe) {
            throw new \Exception(__('Arquivo cadastrado e aguardando importação.'), 400);
        }

        $entidade = $this->novo();
        try {

            $entidade->arquivo_upload = $arquivo;
            $entidade->tipo = $tipo;
            $entidade->titulo = $titulo;
            $entidade->criado = Time::now();
            $entidade->tentativa_importacao = 0;
            $entidade->importando = false;
            $entidade->importado = false;
            $entidade->observacoes = null;
            $entidade->observacoes_erro = null;
            $entidade->usuario_id = $userSession['id'];
            $entidade->mais_parametros = !empty($args) ? implode(',', $args) : null;

            $retorno = $this->save($entidade);

            $this->retorno['entidade'] = $entidade;

            if (!$retorno) {
                $this->retorno['status'] = false;
                $this->retorno['mensagem'] = montaMensagemErros($entidade->getErrors());
                $conn->rollback();
                return $this->retorno;
            }
        } catch (\PDOException $e) {

            $this->retorno['status'] = false;
            $this->retorno['entidade'] = $entidade;
            $this->retorno['mensagem'] = $e->getMessage();
            $conn->rollback();
            return $this->retorno;
        }

        $conn->commit();

        return $this->retorno;
    }

    public function buscarImportar($id)
    {
        $entidade = $this->buscar($id);

        if($entidade->importando && $entidade->inicio_importacao >= Time::now()->modify('-7 minutes')){

            $this->retorno['status'] = false;
            $this->retorno['mensagem'] = 'Arquivo já está sendo importado, iniciou na data de ' . dateToDataTime($entidade->inicio_importacao) . '.';
        }else if($entidade->importado){

            $this->retorno['status'] = false;
            $this->retorno['mensagem'] = 'Arquivo já foi importado na data de ' . dateToDataTime($entidade->final_importacao) . '.';
        }else if(!file_exists (str_replace('/', DS, WWW_ROOT . $entidade->arquivo))){

            $this->retorno['status'] = false;
            $this->retorno['mensagem'] = 'Arquivo não foi encontrado no sistema.';
        }else{

            $entidade->importando = true;
            $entidade->inicio_importacao = Time::now();
            $entidade->tentativa_importacao +=1;

            $this->save($entidade);
        }

        $this->retorno['entidade'] = $entidade;

        return $this->retorno;
    }

    public function iniciaImportacao($id)
    {
        $entidade = $this->buscar($id);
        $entidade->importando = true;
        $entidade->inicio_importacao = Time::now();
        $entidade->tentativa_importacao = $entidade->tentativa_importacao + 1;

        $this->save($entidade);
    }

    public function finalizaImportacao($id, $observacoes = '', $mensagensErro = '')
    {
        $entidade = $this->buscar($id);

        if($mensagensErro !== ''){
            $entidade->observacoes_erro = $mensagensErro
                . "\n------------\n"
                . $entidade->observacoes_erro;
        }

        $entidade->observacoes = $observacoes;
        $entidade->importado = true;
        $entidade->importando = false;
        $entidade->final_importacao = Time::now();

        $this->save($entidade);

        $this->enviarMensagem($entidade);
    }

    public function enviarMensagem($entidade)
    {
        $mensagensTable = TableRegistry::get('UsuariosMensagens');
        $mensagem = $mensagensTable->novo();

        $mensagem->titulo = $entidade->titulo;
        $mensagem->assunto = "Arquivo do tipo \"{$entidade->tipo}\" importado na data de " . Time::now() . ".";
        $mensagem->mensagem = $entidade->observacoes;
        $mensagem->tipo = $entidade->titulo;
        $mensagem->usuario_id = $entidade->usuario_id;
        $mensagem->enviado_por_id = null;
        $mensagem->visualizado = false;
        $mensagem->data_visualizacao = null;
        $mensagem->criado = Time::now();

        $mensagensTable->save($mensagem);
    }

    public function getLastUpdate()
    {
        $last = $this
            ->find()
            ->select()
            ->orderDesc('criado')
            ->first();

        return $last->criado ?? null;
    }
}

src/Template/Element/admin/pessoas/endereco.ctp
<?= $this->Form->hidden('endereco_id', ['value' => @$entidade->id]); ?>
<div class="box-body">
    <div class="form-group col-md-3">
        <?=
        $this->Form->control('cep', [
            'label' => 'CEP',
            'class' => 'cep',
            'value' => cep(@$entidade->cep)
        ]);
        ?>
    </div>
    <div class="form-group col-md-4">
        <?=
        $this->Form->control('rua', [
            'label' => 'Rua',
            'value' => @$entidade->rua
        ]);
        ?>
    </div>
    <div class="form-group col-md-2">
        <?=
        $this->Form->control('numero', [
            'label' => 'Nº',
            'value' => @$entidade->numero
        ]);
        ?>
    </div>
    <div class="form-group col-md-3">
        <?=
        $this->Form->control('complemento', [
            'label' => 'Complemento',
            'value' => @$entidade->complemento
        ]);
        ?>
    </div>
    <div class="form-group col-md-3">
        <?=
        $this->Form->control('bairro', [
            'label' => 'Bairro',
            'value' => @$entidade->bairro
        ]);
        ?>
    </div>
    <div class="form-group col-md-4">
        <?=
        $this->Form->control('cidade', [
            'label' => 'Cidade',
            'value' => @$entidade->cidade
        ]);
        ?>
    </div>
    <div class="form-group col-md-2">
        <?=
        $this->Form->control('uf', [
            'label' => 'UF',
            'maxlength' => 2,
            'value' => @$entidade->uf
        ]);
        ?>
    </div>
</div>

src/Template/Element/admin/pessoas/pessoa-fisica.ctp
<?= $this->Form->hidden('pessoa_fisica_id', ['value' => $entidade->id]); ?>
<div class="row">
    <div class="form-group col-md-4">
        <?=
        $this->Form->control('nome', [
            'required' => true,
            'label' => 'Nome',
            'value' => $entidade->nome
        ]);
        ?>
    </div>
    <div class="form-group col-md-4">
        <?=
        $this->Form->control('data_nascimento', [
            'label' => 'Data Nascimento',
            'class' => 'datepicker',
            'value' => dateToData($entidade->data_nascimento)
        ]);
        ?>
    </div>
    <div class="form-group col-md-4">
        <?=
        $this->Form->control('email', [
            'label' => 'E-mail',
            'value' => $entidade->email
        ]);
        ?>
    </div>
    <div class="form-group col-md-4">
        <?=
        $this->Form->control('cpf', [
            'label' => 'CPF',
            'class' => 'cpf',
            'value' => cpf($entidade->cpf)
        ]);
        ?>
    </div>
    <div class="form-group col-md-4">
        <?=
        $this->Form->control('rg', [
            'label' => 'RG',
            'value' => $entidade->rg
        ]);
        ?>
    </div>
    <div class="form-group col-md-4 radio-booton">
        <label class=" no-padding" for="sexo">Sexo</label>
        <div class="radio">
            <?=
            $this->Form->radio('sexo', sexo(), [
                'required' => true,
                'label' => 'Sexo',
                'value' => $entidade->sexo
            ]);
            ?>
        </div>
    </div>
</div>

src/Template/Element/admin/pessoas/usuario.ctp
<?php
$placeholder = !empty($entidade->id) ? 'Só preencher se for alterar' : '';
$required = empty($entidade->id) ? true : false;
?>
<?= $this->Form->hidden('usuario_id', ['value' => $entidade->id]); ?>
<div class="box-body">
    <div class="form-group col-md-4">
        <?= $this->Form->control('usuario', ['label' => 'Usuário', 'value' => $entidade->usuario, 'required' => true]); ?>
    </div>
    <div class="form-group col-md-4">
        <?=
        $this->Form->control('senha', [
            'label' => 'Senha',
            'type' => 'password',
            'value' => '',
            'placeholder' => $placeholder,
            'required' => $required,
        ]);
        ?>
    </div>
    <div class="form-group col-md-4">
        <?=
        $this->Form->control('confirmar_senha', [
            'label' => 'Confirmar Senha',
            'type' => 'password',
            'value' => '',
            'placeholder' => $placeholder,
            'required' => $required,
        ]);
        ?>
    </div>
    <div class="form-group col-md-4">
        <?=
        $this->element('admin/select2', [
            'controller' => 'niveis',
            'name' => 'niveis_id',
            'label' => 'Níveis',
            'multiple' => false,
            'required' => true,
            'value' => $entidade->niveis_id,
            'placeholder' => 'Pesquise o Nível de Permissão'
        ])
        ?>
    </div>
    <div class="form-group col-md-4 radio-booton">
        <label class=" no-padding" for="ativo">Ativo</label>
        <div class="radio">
            <?=
            $this->Form->radio('ativo', ['1' => 'Sim', '0' => 'Não'], [
                'label' => 'Ativo',
                'value' => !empty($entidade->ativo) ? $entidade->ativo : 1,
                'required' => true,
            ]);
            ?>
        </div>
    </div>
    <div class="form-group col-md-4">
        <?php
        if (empty($entidade->imagem)) {
            echo $this->Form->control('imagem_upload', [
                'type' => 'file',
                'class' => 'upload_crop',
                'multiple' => false,
                'accept' => 'image/*',
                'label' => 'Imagem'
            ]);
        } else {
            ?>
            <div class="col-md-4 no-padding">
                <strong>Imagem</strong>
                <?= $this->Html->image('../' . $entidade->imagem, ['class' => 'img-responsive img-usuario img-thumbnail']); ?>
            </div>
            <div class="col-md-2 text-rigth">
                <?=
                $this->Html->link("<i class='fa fa-trash'></i> Excluir", ['controller' => 'Usuarios', 'action' => 'excluir_imagem', $entidade->id, '_full' => true], [
                    "alt" => "Imagem",
                    'escape' => false,
                    'confirm' => __('Tem certeza de que deseja excluir o arquivo?'),
                    'class' => 'btn btn-xs btn-danger tex'
                ]);
                ?>
            </div>
        <?php } ?>
        <div id="uploaded_image"></div>
    </div>
</div>
<?= $this->element('admin/imagem-crop-modal') ?>